Multi-Document Content Rendering ← (Spike) (#99)
* DSL: tripple level sub-heading

* stub in README's

Demarcating the shape of the "system" (TDD, production grade level engineering) of UI related modules.

Folder structures establishes a clear namespace around "UI Frameworks" allowing de-coupling from any one medium-term level "UI Rendering Technology Fashion"

** hopefully the ones here represent long-lived "fashions" - but the system itself is not tied to it.
See https://github.com/cellplatform/platform-0.2.0/blob/main/README.md#evolution-strategy

* spike

* bump

* tweak

* bump

* rename

* tweak

* refactor: Remove React imports (no longer needed)

* builder: assets output directory rename => "lib"

* refactor: root layout

* refactor

* Stub in Markdown document

* update refs

* Text.Is

* comments

* export Patch

* builder: compile paths using relative base.

* spike

* spike

* spike: holding pattern

* spike

* Update Root.HoldingPattern.tsx

* spike

* spike

* Ignore markdown

* Move [Path] from sys.fs => sys.util

* spike

* rename field

* Update History.tsx

* Export combined MD AST types.

* run dev server on port: 1234

* Holding Pattern

* MD helpers

* layout (spike)

* Click handler on Outline

* refactor

* spike: outline selection and state loading

* Version History Panel - tweaks

* spike

* Fetch public log helper (DRY)

* refactor: move Fetch into common

* tweak

* tweak

* copy over template (Bus/Controller setup)

* refactor

* rename

* change favicon

* refactor

* stub in bus controller

* tweak

* default singleton instance

* spin up controller in Root.

* sys.util - export takeUntil RXJS operator

💦💦

  NOTE: The take-until RXJS operator is exported here
  to avoid an error occuring when the module is bundled.

💦

Error Condition:

    const { dispose$ } from rx.disposable()
    takeUtil(dispose$)

Will throw (as of Sep 2022):

    ERROR: "TypeError: You provided an invalid object where a stream was expected."

This is realted to the use of Symbols getting munged somehow during bundling within
the check RXJS makes of the observable that is passed into the [takeUtil] function.

* sys.util - Rx: export common operators

* report /types.d/ folder size on build

* bump

* reading outline from State

* tmpl: refactor

* tmpl: file rename

* Editor loading

* refactor

* refactor

* spike

* state tree and bus controller refactoring

* spike

* spike

* spike

* spike

* rename

* update refs

* spike: selection state

* spike: State Change via event-bus passed fn() <== MutationHandler

* spike - root entry UI

* spike - entry refactor

* audit before publish

* spike: setup folder structure: "ui.react.libs"

* spike: Tauri related stuff

* stub in module: sys.ui.react

* move folder

* prep: sys.ui.react.common

* timeout

* refactor

* MDAST test: tree

* setup

* visit mutation helper callback

* AST mutation - hProperties => HTML image element output

* refactor

* toString - narrow to Position

* remove narrower when on HTML

* refactor

* scenario test

* Update Processor.TEST.mts

* fix call-site

* refactor

* markdown process image - include "src" attribute.

* file rename

* Update Processor.TEST.mts

* refactor

* Markdown: { Is } and { Find }

* return mdast and hast from root response

* md parser - support width/height hProperties

* export from module root

* render custom <Component> from markdown AST (Spike)

* fix: public log being written

* no selection

* rendering markdown

* bndle