Blob Storage: 🌳  ←  (spike) (#163)
* update module template - .mts → .ts

* sub in module: ext.vercel.blob

* add: @vercel/blob

* add: @automerge/automerge-repo

* spike: dev: → spin up local spec (for demo composition)

* ignore .vercel

* build

* spike: expose blob

* module: blob.edge (dedicated module for server deployment)

* to Blue

* build

* close icon only when enabled

* clean up

* refactor Blob sample

* button color → white

* export dynamic loader: UI

* update refs

* build

* Update ui.ConnectButton.tsx

* Update entry.Specs.mts

* Update libs.mts

* insert WebRTC connector (UI)

* Auth (Privy) - updates while placing within Dev.000 (Spike)

* Config - only add polyfills when running in "dev" mode

* update refs

* PropList, refactor spec

* Login in [dev.000] spike

* export <Info>

* Fire clean event for network (CRDT) changes

* additional type

* dev.000 - network data

* dev.000 - use <GroupVideo> component

* refactor

* Compiler: do not build non-vite modules

* build

* update sample

* sample: vercel edge function

* tweak debug output

* tweak label

* blob - edge function sample (not working)

As a pure (non-NextJS) implementation on an edge function, currently the Edge deployment throws an error while building:

Error: The Edge Function "api/list" is referencing unsupported modules:
        - @vercel: crypto
        - busboy: stream
        - undici: stream, net, tls, http, querystring, stream/web, util/types, worker_threads, zlib, perf_hooks, console, url, crypto, diagnostics_channel

This comes from referencing

   import { list } from '@vercel/blob';

The NextJS sample code that uses the same library does not cause this build error on deployment.

Refs:
- https://vercel.com/docs/storage/vercel-blob/quickstart
- https://vercel.com/docs/storage/vercel-blob/using-blob-sdk

* WIP: blob UI samples

* dev.000 → tweak App

* Update yarn.lock

* fix (tmp)

* update refs

* regress nanoid

* update refs

* tmp fix

* try: break workflow up

* revert CI action

* quick pass