blob - edge function sample (not working)
As a pure (non-NextJS) implementation on an edge function, currently the Edge deployment throws an error while building:

Error: The Edge Function "api/list" is referencing unsupported modules:
        - @vercel: crypto
        - busboy: stream
        - undici: stream, net, tls, http, querystring, stream/web, util/types, worker_threads, zlib, perf_hooks, console, url, crypto, diagnostics_channel

This comes from referencing

   import { list } from '@vercel/blob';

The NextJS sample code that uses the same library does not cause this build error on deployment.

Refs:
- https://vercel.com/docs/storage/vercel-blob/quickstart
- https://vercel.com/docs/storage/vercel-blob/using-blob-sdk